FROM openjdk:9
MAINTAINER malekayadi <malek1505@gmail.com>
#ADD target/rxreactive-0.0.1-SNAPSHOT.jar rxreactive-0.0.1-SNAPSHOT.jar
#EXPOSE 8080
#ENTRYPOINT ["java","-jar" , "rxreactive-0.0.1-SNAPSHOT.jar"]
